package(default_visibility = ["//visibility:public"])

java_library(
    name = "context_free",
    srcs = [
        "ContextFreeGrammar.java",
        "ContextFreeSet.java",
        "Epsilon.java",
        "GrammarSymbol.java",
        "Item.java",
        "LR1Item.java",
        "NonTerminal.java",
        "Production.java",
        "Terminal.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/grammar",
        "//src/org/inxar/syntacs/util",
    ],
)
