package(default_visibility = ["//visibility:public"])

java_library(
    name = "pushdown",
    srcs = [
        "Action.java",
        "AmbiguityException.java",
        "DPA.java",
        "DPAConstructor.java",
        "DPATransformer.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/grammar/context_free",
        "//src/org/inxar/syntacs/util",
    ],
)
