/**
 * Copyright (C) 2001 Paul Cody Johnston - pcj@inxar.org
 * @author Paul Cody Johnston - pcj@inxar.org
 */
package com.inxar.syntacs.translator.syntacs;

import com.inxar.syntacs.automaton.finite.MesoArrayDFA;
import com.inxar.syntacs.util.Pickler;

/**
 * Automatically generated by <a href='http://www.inxar.org/syntacs'>Syntacs
 *  Translation Toolkit</a> on Fri Jul 06 12:05:11 PDT 2001
 */
class SyntacsDefaultDFA
extends MesoArrayDFA
{
    private static final int[][] _table;
    private static final int[] _accepts;
    
    SyntacsDefaultDFA()
    {
        super(_table, _accepts);
    }
    
    static {
        _table = Pickler.unpickle2D(" 2 $! \u8001\u001f\u8001\u001f     \u0096 ) \u009a     # # #   #                                     #   $ \"                 %       \' \' \' \' \' \' \' \' \' \'   &   (       ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )         )   ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ( * - \" \" 0 \" \" 1 < ) @     # # #   #                                     # _ B | $ $ / $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ . $! \u8001\u001f\u8001\u001f     $! \u8001\u001f\u8001\u001f     0 N Y     *   \' \' \' \' \' \' \' \' \' \' $! \u8001\u001f\u8001\u001f     r M \u009a     )     ) ) ) ) ) ) ) ) ) )               ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )         )   ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) . P Y     + + + + + + + + + + 0 N Y     ,   + + + + + + + + + + . P Y     - - - - - - - - - - . P Y     - - - - - - - - - - % * * $ $   $! \u8001\u001f\u8001\u001f     $! \u8001\u001f\u8001\u001f     % * *     0");
        _accepts = Pickler.unpickle1D(" 2\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f \"\u8001\u001f\u8001\u001f 6 7\u8001\u001f\u8001\u001f 8 3\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f 5\u8001\u001f\u8001\u001f 4 !\u8001\u001f\u8001\u001f");
    } 
}