/**
 * Copyright (C) 2001 Paul Cody Johnston - pcj@inxar.org
 * @author Paul Cody Johnston - pcj@inxar.org
 */
package com.inxar.syntacs.translator.test;

import com.inxar.syntacs.automaton.pushdown.MesoArrayDPA;
import com.inxar.syntacs.util.Pickler;

/**
 * Automatically generated by <a href='http://www.inxar.org/syntacs'>Syntacs
 *  Translation Toolkit</a> on Fri Jul 06 12:04:58 PDT 2001
 */
class AbbDPA
extends MesoArrayDPA
{
    
    AbbDPA()
    {
        super(_action, _go, _actions);
    }
    private static int[][] _action;
    private static int[] _actions;
    private static int[][] _go;
    
    static {
        _action = Pickler.unpickle2D(" # # ! ! ! #     # #     \"");
        _go = Pickler.unpickle2D(" ! # \" \" \"");
        _actions = Pickler.unpickle1D(" $  0!P @ ");
    } 
}