/**
 * Copyright (C) 2016 Paul Cody Johnston - pcj@inxar.org
 * @author Paul Cody Johnston - pcj@inxar.org
 */
package com.inxar.syntacs.translator.test;

import org.inxar.syntacs.translator.Translator;
import org.inxar.syntacs.translator.lr.LRTranslator;
import org.inxar.syntacs.translator.lr.LRTranslatorGrammar;
import org.inxar.syntacs.util.IntArray;
import com.inxar.syntacs.util.ArrayIntArray;
import org.inxar.syntacs.automaton.finite.DFA;
import org.inxar.syntacs.analyzer.Input;
import org.inxar.syntacs.analyzer.lexical.Lexer;
import org.inxar.syntacs.analyzer.syntactic.Parser;
import org.inxar.syntacs.translator.lr.LRTranslatorInterpreter;
import java.util.Properties;

/**
 * Automatically generated by <a href='http://www.inxar.org/syntacs'>Syntacs
 *  Translation Toolkit</a> on Tue Oct 11 20:47:25 MDT 2016<P><PRE># GRAMMAR
 *  DECLARATION
 * this is abb version 0.0.1;
 * 
 * # PROPERTY DEFINITIONS
 * property viz-namespace = "abb";
 * property viz-syntactic = "true";
 * property author-email = "pcj@inxar.org";
 * property author = "Paul Cody Johnston";
 * property viz-sourcepath = "./grammar";
 * property viz-lexical = "true";
 * property compile-namespace = "com.inxar.syntacs.translator.test";
 * property compile-dpa-constructor-method = "LALR1";
 * property compile-sourcepath = "./src";
 * 
 * # TERMINAL DECLARATIONS
 * terminal ABB;
 * 
 * # TERMINAL DEFINITIONS
 * ABB matches " (a|b)*abb ";
 * 
 * # NONTERMINAL DECLARATIONS
 * nonterminal Goal;
 * 
 * # NONTERMINAL DEFINITIONS
 * reduce Goal when ABB;
 * 
 * accept when Goal;
 * 
 * # CONTEXT DECLARATIONS
 * context default;
 * 
 * # CONTEXT DEFINITIONS
 * default includes ABB;
 * 
 * start in context default;
 * 
 * </PRE>
 */
public class AbbGrammar
implements LRTranslatorGrammar
{
    
    /**
     * Constant ID for default
     */
    public static final int C_default = 0;
    
    /**
     * Terminal ID for ABB
     */
    public static final int T_ABB = 1;
    
    /**
     * NonTerminal ID for Goal
     */
    public static final int N_Goal = 2;
    
    /**
     * Production ID for Goal__ABB
     */
    public static final int P_Goal__ABB = 0;
    
    public String getContext(int ID)
    {
        switch (ID) {
            case 0: {
                return "default";
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public int getContextAction(int cID, int tID)
    {
        switch (cID) {
            case 0: {
                return getDefaultContextAction(tID);
            } 
            default: {
                return -2147483647;
            } 
        } 
    }
    
    public int getContextRegister(int cID, int tID)
    {
        switch (cID) {
            case 0: {
                return getDefaultContextRegister(tID);
            } 
            default: {
                return -2147483647;
            } 
        } 
    }
    
    public IntArray getContextTerminals(int ID)
    {
        switch (ID) {
            case 0: {
                return new ArrayIntArray(contextTerminals[0]);
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public IntArray getContexts()
    {
        return contexts;
    }
    
    public int getGoalNonTerminal()
    {
        return 2;
    }
    
    public String getName()
    {
        return "abb";
    }
    
    public String getNonTerminal(int ID)
    {
        switch (ID) {
            case 2: {
                return "Goal";
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public IntArray getNonTerminals()
    {
        return nonTerminals;
    }
    
    public String getProduction(int ID)
    {
        switch (ID) {
            case 0: {
                return "Goal: ABB";
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public int getProductionLength(int ID)
    {
        switch (ID) {
            case 0: {
                return 1;
            } 
            default: {
                return -2147483644;
            } 
        } 
    }
    
    public int getProductionNonTerminal(int ID)
    {
        switch (ID) {
            case 0: {
                return 2;
            } 
            default: {
                return -2147483644;
            } 
        } 
    }
    
    public IntArray getProductionSymbols(int ID)
    {
        switch (ID) {
            case 0: {
                return new ArrayIntArray(productionSymbols[0]);
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public IntArray getProductions()
    {
        return productions;
    }
    
    public int getStartContext()
    {
        return 0;
    }
    
    public String getTerminal(int ID)
    {
        switch (ID) {
            case 1: {
                return "ABB";
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public IntArray getTerminalContexts(int ID)
    {
        switch (ID) {
            case 1: {
                return new ArrayIntArray(terminalContexts[0]);
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public Object getTerminalRegexp(int ID)
    {
        switch (ID) {
            case 1: {
                return " (a|b)*abb ";
            } 
            default: {
                return null;
            } 
        } 
    }
    
    public IntArray getTerminals()
    {
        return terminals;
    }
    
    public String getVersion()
    {
        return "0.0.1";
    }
    
    public Translator newTranslator()
    {
        return newTranslator(null);
    }
    
    public Translator newTranslator(Properties p)
    {
        LRTranslator t = new com.inxar.syntacs.translator.lr.StandardLRTranslator();
        t.setLRTranslatorGrammar(this);
        t.setProperties(p);
        Input input = new com.inxar.syntacs.analyzer.StandardInput();
        t.setInput(input);
        Lexer lexer = new com.inxar.syntacs.analyzer.lexical.StandardLexer();
        t.setLexer(lexer);
        Parser parser = new com.inxar.syntacs.analyzer.syntactic.StandardParser();
        t.setParser(parser);
        LRTranslatorInterpreter interp = new com.inxar.syntacs.translator.lr.StandardLRTranslatorInterpreter();
        t.setLRTranslatorInterpreter(interp);
        lexer.initialize(new DFA[]{new AbbDefaultDFA()});
        parser.initialize(new AbbDPA());
        return t;
    }
    
    private int getDefaultContextAction(int tID)
    {
        switch (tID) {
            case 1: {
                return 1;
            } 
            default: {
                return -2147483646;
            } 
        } 
    }
    
    private int getDefaultContextRegister(int tID)
    {
        switch (tID) {
            case 1: {
                return 0;
            } 
            default: {
                return -2147483646;
            } 
        } 
    }
    private int[][] contextTerminals = new int[][]{{1}};
    private IntArray contexts = new ArrayIntArray(new int[]{0});
    private IntArray nonTerminals = new ArrayIntArray(new int[]{2});
    private int[][] productionSymbols = new int[][]{{1}};
    private IntArray productions = new ArrayIntArray(new int[]{0});
    private int[][] terminalContexts = new int[][]{{0}};
    private IntArray terminals = new ArrayIntArray(new int[]{1});
}