/**
 * Copyright (C) 2001 Paul Cody Johnston - pcj@inxar.org
 * @author Paul Cody Johnston - pcj@inxar.org
 */
package com.inxar.syntacs.translator.test;

import com.inxar.syntacs.automaton.pushdown.MesoArrayDPA;

/**
 * Automatically generated by <a href='http://www.inxar.org/syntacs'>Syntacs
 *  Translation Toolkit</a> on Fri Jul 06 12:05:01 PDT 2001
 */
class EtfDPA
extends MesoArrayDPA
{
    
    EtfDPA()
    {
        super(_action, _go, _actions);
    }
    
    private static void initAction()
    {
        _action = new int[14][];
        _action[0] = new int[]{3, 5, 1, 0, 2};
        _action[1] = new int[]{3, 5, 1, 0, 2};
        _action[2] = new int[]{0, 4, 7, 7, 7, 0, 7};
        _action[3] = new int[]{1, 4, 3, 0, 0, 5};
        _action[4] = new int[]{3, 5, 1, 0, 2};
        _action[5] = new int[]{0, 4, 12, 12, 4, 0, 12};
        _action[6] = new int[]{3, 5, 1, 0, 2};
        _action[7] = new int[]{0, 4, 10, 10, 10, 0, 10};
        _action[8] = new int[]{0, 4, 9, 9, 9, 0, 9};
        _action[9] = new int[]{0, 4, 8, 8, 8, 0, 8};
        _action[10] = new int[]{0, 4, 11, 11, 4, 0, 11};
        _action[11] = new int[]{0, 0, 6};
        _action[12] = null;
        _action[13] = new int[]{0, 1, 13, 3};
    }
    
    private static void initActions()
    {
        _actions = new int[]{0, 1048577, 1048578, 1048580, 1048582, 1048585, 3145728, 2097158, 2097157, 2097156, 2097155, 2097154, 2097153, 2097152};
    }
    
    private static void initGo()
    {
        _go = new int[7][];
        _go[0] = new int[]{6, 9, 11, 13, 10, 8};
        _go[1] = new int[]{7, 9, 3, 10, 8};
        _go[2] = null;
        _go[3] = null;
        _go[4] = new int[]{8, 9, 5, 8};
        _go[5] = null;
        _go[6] = new int[]{9, 9, 7};
    }
    private static int[][] _action;
    private static int[] _actions;
    private static int[][] _go;
    
    static {
        initAction();
        initGo();
        initActions();
    } 
}