package(default_visibility = ["//visibility:public"])

java_library(
    name = "translator",
    srcs = [
        "Auditor.java",
        "Complaint.java",
        "Translator.java",
        "TranslatorGrammar.java",
        "TranslationException.java",
        "RuntimeTranslationException.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/analyzer",
    ],
)
