package(default_visibility = ["//visibility:public"])

java_library(
    name = "context_free",
    srcs = [
        "CFEpsilon.java",
        "CFGrammar.java",
        "CFItem.java",
        "CFLR1Item.java",
        "CFNonTerminal.java",
        "CFProduction.java",
        "CFTerminal.java",
    ],
    deps = [
        "//src/com/inxar/syntacs/util",
        "//src/com/inxar/syntacs/util:session",
        "//src/com/inxar/syntacs/util:string",
        "//src/org/inxar/syntacs/grammar",
        "//src/org/inxar/syntacs/grammar/context_free",
        "//src/org/inxar/syntacs/util",
        "//src/org/inxar/syntacs/util:session",
    ],
)
