package(default_visibility = ["//visibility:public"])

java_import(
    name = "xerces",
    jars = [
        "xerces.jar",
    ],
)

java_import(
    name = "jenesis",
    jars = [
        "jenesis.jar",
    ],
)

java_library(
    name = "junit4",
    exports = [
        "@junit_junit_4//jar",
    ],
)
