package(default_visibility = ["//visibility:public"])

java_library(
    name = "regular",
    srcs = [
        "CharClass.java",
        "CharString.java",
        "Concatenation.java",
        "ExpressionTerminator.java",
        "Option.java",
        "Interval.java",
        "RegularExpression.java",
        "RegularToken.java",
        "RegularGrammar.java",
        "RegularSet.java",
        "Closure.java",
        "PositiveClosure.java",
        "Epsilon.java",
        "Union.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/grammar",
        "//src/org/inxar/syntacs/util",
    ]
)
