/**
 * Copyright (C) 2001 Paul Cody Johnston - pcj@inxar.org
 * @author Paul Cody Johnston - pcj@inxar.org
 */
package com.inxar.syntacs.translator.regexp;

import com.inxar.syntacs.automaton.finite.MesoArrayDFA;
import com.inxar.syntacs.util.Pickler;

/**
 * Automatically generated by <a href='http://www.inxar.org/syntacs'>Syntacs
 *  Translation Toolkit</a> on Fri Jul 06 12:05:08 PDT 2001
 */
class RegexpCharclassDFA extends MesoArrayDFA {
  private static final int[][] _table;
  private static final int[] _accepts;

  RegexpCharclassDFA() {
    super(_table, _accepts);
  }

  static {
    _table =
        Pickler.unpickle2D(
            " 2 $! \u8001\u001f\u8001\u001f     y ) } # # \" \" \" # \" # # # # # # # # # # # # # # # # # # \" # # # # # # # # # # # # $ # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # % & ; * @     1 1   1                                     1 $! \u8001\u001f\u8001\u001f     $! \u8001\u001f\u8001\u001f     \u0091 ) \u0095 ( (       (   ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( (   ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( \' ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ( ) $! \u8001\u001f\u8001\u001f     ( P S     . . . . $! \u8001\u001f\u8001\u001f     [ P \u0086     * * * * * * * * * *               * * * * * *                                                     * * * * * * [ P \u0086     + + + + + + + + + +               + + + + + +                                                     + + + + + + [ P \u0086     , , , , , , , , , ,               , , , , , ,                                                     , , , , , , [ P \u0086     - - - - - - - - - -               - - - - - -                                                     - - - - - - $! \u8001\u001f\u8001\u001f     , P W     / / / / / / / / , P W     0 0 0 0 0 0 0 0 $! \u8001\u001f\u8001\u001f     < ) @     1 1 1   1                                     1");
    _accepts =
        Pickler.unpickle1D(
            " 2\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f ! # /\u8001\u001f\u8001\u001f . 0 0 0\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f 2\u8001\u001f\u8001\u001f\u8001\u001f\u8001\u001f 1 !");
  }
}
