package(default_visibility = ["//visibility:public"])

java_library(
    name = "lexical",
    srcs = [
        "StandardLexer.java",
    ],
    deps = [
        "//src/com/inxar/syntacs/translator/lr:component",
        "//src/com/inxar/syntacs/util",
        "//src/com/inxar/syntacs/util:session",
        "//src/org/inxar/syntacs/analyzer",
        "//src/org/inxar/syntacs/analyzer/lexical",
        "//src/org/inxar/syntacs/automaton/finite",
        "//src/org/inxar/syntacs/grammar",
        "//src/org/inxar/syntacs/translator",
        "//src/org/inxar/syntacs/translator/lr:grammar",
        "//src/org/inxar/syntacs/translator/lr:translator",
        "//src/org/inxar/syntacs/util",
        "//src/org/inxar/syntacs/util:session",
    ],
)
