package(default_visibility = ["//visibility:public"])

java_library(
    name = "syntactic",
    srcs = [
        "Correction.java",
        "Parser.java",
        "ParserInterpreter.java",
        "Recovery.java",
        "Sentence.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/analyzer",
        "//src/org/inxar/syntacs/translator",
        "//src/org/inxar/syntacs/translator/lr:component",
    ],
)
