package(default_visibility = ["//visibility:public"])

java_library(
    name = "translator",
    srcs = [
        "StandardAuditor.java",
    ],
    deps = [
        "//src/org/inxar/syntacs/analyzer",
        "//src/org/inxar/syntacs/translator",
        "//src/com/inxar/syntacs/util:string",
        "//src/org/inxar/syntacs/util:session",
        "//src/com/inxar/syntacs/util:session",
    ],
)
