package(default_visibility = ["//visibility:public"])

java_library(
    name = "finite",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/org/inxar/syntacs/grammar/regular",
    ],
)
